/*
Project Euler #2: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1,2,3,5,8,13,21,34,55,89,⋯
By considering the terms in the Fibonacci sequence whose values do not exceed N, find the sum of the even-valued terms. 

complete problem statement can be found at:-
https://www.hackerrank.com/contests/projecteuler/challenges/euler002

*/


#include <stdio.h>

int main() {
  
    int t;
    scanf("%d",&t);
    unsigned long a;
    unsigned long long sum=0;
    while(t>=1){
        sum=0;
        scanf("%lu",&a);
        
        
        unsigned long long first=0,second=2, third;
        if(a>=2)
            sum=2;
        for(third=4*second+first;third<=a;third=4*second+first)
        {
          sum+=third;
            first=second;
            second=third;
        }
        printf("%llu\n",sum);
    t--;
    }
    return 0;
    }
